[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "keyfile.toml"

[falltergeist]
source = "github"
github = "falltergeist/falltergeist"
use_latest_release = true

[ffmpeg-headless]
source = "git"
git = "https://git.ffmpeg.org/ffmpeg.git"
prefix = "n"
exclude_regex = "(v.*|.*-dev)"

[gallery-dl]
source = "github"
github = "mikf/gallery-dl"
prefix = "v"
use_latest_release = true

#[hunspell-sv]
#source = "cmd"
#cmd = '''curl -s https://extensions.libreoffice.org/en/extensions/show/swedish-spelling-dictionary-den-stora-svenska-ordlistan | grep releaseRow -A1 -m2 | grep -Po "\d+.\d+"'''

[komga]
source = "github"
github = "gotson/komga"
prefix = "v"
use_latest_release = true

[libva-headless]
source = "github"
github = "intel/libva"
use_latest_tag = true

[qimgv-light]
source = "github"
github = "easymodo/qimgv"
prefix = "v"
use_latest_release = true

[libjodycode]
source = "github"
github = "jbruchon/libjodycode"
prefix = "v"
use_max_tag = true

[jdupes]
source = "github"
github = "jbruchon/jdupes"
prefix = "v"
use_latest_tag = true
