[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "keyfile.toml"

[conky-katt]
source = "github"
github = "brndnmtthws/conky"
prefix = "v"
use_latest_release = true

[ffmpeg-headless]
source = "git"
git = "https://git.ffmpeg.org/ffmpeg.git"
prefix = "n"
exclude_regex = "(v.*|.*-dev)"

[gallery-dl]
source = "github"
github = "mikf/gallery-dl"
prefix = "v"
use_latest_release = true

[godotpcktool-bin]
source = "github"
github = "hhyyrylainen/GodotPckTool"
prefix = "v"
use_latest_release = true

[hunspell-sv]
source = "cmd"
cmd = '''curl -s https://extensions.libreoffice.org/en/extensions/show/swedish-spelling-dictionary-den-stora-svenska-ordlistan | grep releaseRow -A1 -m2 | grep -Po "\d+.\d+"'''

[kio-noslowremote]
source = "archpkg"
archpkg = "kio"
strip_release = true

[lib32-mozjpeg]
source = "aur"
aur = "mozjpeg"
strip_release = true

[libva-headless]
source = "github"
github = "intel/libva"
use_latest_tag = true

[powerdevil-light]
source = "archpkg"
archpkg = "powerdevil"
strip_release = true

[qimgv-light]
source = "github"
github = "easymodo/qimgv"
prefix = "v"
use_latest_release = true

[shellcheck-bin]
source = "github"
github = "koalaman/shellcheck"
prefix = "v"
use_latest_release = true
