# paru
alias paconf='paru -Pg'
alias paupg='paru -Syu'
alias pasu='paru -Syu --noconfirm'
alias pain='paru -S'
alias pains='paru -U'
alias pare='paru -R'
alias parem='paru -Rns'
alias parep='paru -Si'
alias pareps='paru -Ss'
alias paloc='paru -Qi'
alias palocs='paru -Qs'
alias palst='paru -Qe'
alias paorph='paru -Qtd'
alias painsd='paru -S --asdeps'
alias pamir='paru -Syy'
